# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shp2db}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan J. Geyer"]
  s.date = %q{2011-03-18}
  s.default_executable = %q{shp2db}
  s.description = %q{Converts TIGER shapefiles to relational databases using ActiveRecord}
  s.email = %q{me@ryangeyer.com}
  s.executables = ["shp2db"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "NOTICE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/shp2db",
    "lib/stdout.rb",
    "shp2db.gemspec",
    "test/helper.rb",
    "test/test_shp2db.rb"
  ]
  s.homepage = %q{http://github.com/rgeyer/shp2db}
  s.licenses = ["Apache2"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Converts TIGER shapefiles to relational databases using ActiveRecord}
  s.test_files = [
    "test/helper.rb",
    "test/test_shp2db.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<shapelib>, [">= 0.7.0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<shapelib>, [">= 0.7.0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<shapelib>, [">= 0.7.0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

